apiVersion: v1
kind: Service
metadata:
  name: temporal-worker-metrics
  namespace: temporal-demo
spec:
  type: NodePort
  selector:
    app: temporal-worker
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090